/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JsonSchema = {
  /**
   * The document's "primary data" is a representation of the resource or collection of resources targeted by a request.
   */
  data:
    | {
        type: string;
        id: string;
        /**
         * Members of the attributes object ("attributes") represent information about the resource object in which it's defined.
         */
        attributes?: {
          /**
           * Attributes may contain any valid JSON value.
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-zA-Z0-9](?:[-\w]*[a-zA-Z0-9])?$".
           */
          [k: string]: {
            [k: string]: unknown;
          };
        };
        /**
         * Members of the relationships object ("relationships") represent references from the resource object in which it's defined to other resource objects.
         */
        relationships?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-zA-Z0-9](?:[-\w]*[a-zA-Z0-9])?$".
           */
          [k: string]: {
            [k: string]: unknown;
          };
        };
        links?: {
          /**
           * A link **MUST** be represented as either: a string containing the link's URL or a link object.
           */
          [k: string]:
            | string
            | {
                /**
                 * A string containing the link's URL.
                 */
                href: string;
                /**
                 * Non-standard meta-information that can not be represented as an attribute or relationship.
                 */
                meta?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
        };
        /**
         * Non-standard meta-information that can not be represented as an attribute or relationship.
         */
        meta?: {
          [k: string]: unknown;
        };
      }
    | {
        type: string;
        id: string;
        /**
         * Members of the attributes object ("attributes") represent information about the resource object in which it's defined.
         */
        attributes?: {
          /**
           * Attributes may contain any valid JSON value.
           *
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-zA-Z0-9](?:[-\w]*[a-zA-Z0-9])?$".
           */
          [k: string]: {
            [k: string]: unknown;
          };
        };
        /**
         * Members of the relationships object ("relationships") represent references from the resource object in which it's defined to other resource objects.
         */
        relationships?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[a-zA-Z0-9](?:[-\w]*[a-zA-Z0-9])?$".
           */
          [k: string]: {
            [k: string]: unknown;
          };
        };
        links?: {
          /**
           * A link **MUST** be represented as either: a string containing the link's URL or a link object.
           */
          [k: string]:
            | string
            | {
                /**
                 * A string containing the link's URL.
                 */
                href: string;
                /**
                 * Non-standard meta-information that can not be represented as an attribute or relationship.
                 */
                meta?: {
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              };
        };
        /**
         * Non-standard meta-information that can not be represented as an attribute or relationship.
         */
        meta?: {
          [k: string]: unknown;
        };
      }[]
    | null;
  /**
   * To reduce the number of HTTP requests, servers **MAY** allow responses that include related resources along with the requested primary resources. Such responses are called "compound documents".
   */
  included?: {
    type: string;
    id: string;
    /**
     * Members of the attributes object ("attributes") represent information about the resource object in which it's defined.
     */
    attributes?: {
      /**
       * Attributes may contain any valid JSON value.
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-zA-Z0-9](?:[-\w]*[a-zA-Z0-9])?$".
       */
      [k: string]: {
        [k: string]: unknown;
      };
    };
    /**
     * Members of the relationships object ("relationships") represent references from the resource object in which it's defined to other resource objects.
     */
    relationships?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[a-zA-Z0-9](?:[-\w]*[a-zA-Z0-9])?$".
       */
      [k: string]: {
        [k: string]: unknown;
      };
    };
    links?: {
      /**
       * A link **MUST** be represented as either: a string containing the link's URL or a link object.
       */
      [k: string]:
        | string
        | {
            /**
             * A string containing the link's URL.
             */
            href: string;
            /**
             * Non-standard meta-information that can not be represented as an attribute or relationship.
             */
            meta?: {
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
    };
    /**
     * Non-standard meta-information that can not be represented as an attribute or relationship.
     */
    meta?: {
      [k: string]: unknown;
    };
  }[];
  /**
   * Non-standard meta-information that can not be represented as an attribute or relationship.
   */
  meta?: {
    [k: string]: unknown;
  };
  /**
   * Link members related to the primary data.
   */
  links?: {
    /**
     * A link **MUST** be represented as either: a string containing the link's URL or a link object.
     */
    [k: string]:
      | string
      | {
          /**
           * A string containing the link's URL.
           */
          href: string;
          /**
           * Non-standard meta-information that can not be represented as an attribute or relationship.
           */
          meta?: {
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
  } & {
    /**
     * The first page of data
     */
    first?:
      | (
          | string
          | {
              /**
               * A string containing the link's URL.
               */
              href: string;
              /**
               * Non-standard meta-information that can not be represented as an attribute or relationship.
               */
              meta?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }
        )
      | null;
    /**
     * The last page of data
     */
    last?:
      | (
          | string
          | {
              /**
               * A string containing the link's URL.
               */
              href: string;
              /**
               * Non-standard meta-information that can not be represented as an attribute or relationship.
               */
              meta?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }
        )
      | null;
    /**
     * The previous page of data
     */
    prev?:
      | (
          | string
          | {
              /**
               * A string containing the link's URL.
               */
              href: string;
              /**
               * Non-standard meta-information that can not be represented as an attribute or relationship.
               */
              meta?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }
        )
      | null;
    /**
     * The next page of data
     */
    next?:
      | (
          | string
          | {
              /**
               * A string containing the link's URL.
               */
              href: string;
              /**
               * Non-standard meta-information that can not be represented as an attribute or relationship.
               */
              meta?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }
        )
      | null;
    [k: string]: unknown;
  };
  /**
   * An object describing the server's implementation
   */
  jsonapi?: {
    version?: string;
    /**
     * Non-standard meta-information that can not be represented as an attribute or relationship.
     */
    meta?: {
      [k: string]: unknown;
    };
  };
} & {
  [k: string]: unknown;
};
